[project]
id = "trading-pro-mvp"
name = "Trading AI Pro MVP"

[api]
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:8100"
