import { VendorResult } from '../../core/services/ai-sourcing.service';

/**
 * Mock data 12 xưởng: 5 Việt Nam (VND) + 2 Campuchia (USD) + 5 Trung Quốc (CNY)
 * Giá và tiền tệ đúng theo quốc gia
 */
export const MOCK_VENDORS: VendorResult[] = [
  // ========== 5 XƯỞNG VIỆT NAM — VND ==========
  {
    name: 'Xưởng Da Sài Gòn',
    url: 'https://xuongdasaigon.vn/tui-xach-nu-cao-cap',
    price: 350000,
    currency: 'VND',
    moq: 50,
    rating: 4.8,
    years_on_platform: 6,
    location: 'Quận Tân Bình, TP. Hồ Chí Minh',
    phone: '0912 345 678',
    contact_type: 'zalo',
    country: 'VN',
    description: 'Chuyên sản xuất túi xách da thật, balo, ví nữ. Nhận gia công theo mẫu với số lượng từ 50 cái.',
  },
  {
    name: 'Phụ Kiện Thời Trang Hà Nội',
    url: 'https://phukienhn.com/balo-tui-xach',
    price: 180000,
    currency: 'VND',
    moq: 100,
    rating: 4.5,
    years_on_platform: 4,
    location: 'Quận Hoàng Mai, Hà Nội',
    phone: '0978 123 456',
    contact_type: 'zalo',
    country: 'VN',
    description: 'Xưởng chuyên sỉ balo, túi xách thời trang nữ. Giá xưởng, hỗ trợ in logo thương hiệu riêng.',
  },
  {
    name: 'Leather Factory Bình Dương',
    url: 'https://leatherfactory.vn/products',
    price: 520000,
    currency: 'VND',
    moq: 30,
    rating: 4.9,
    years_on_platform: 8,
    location: 'TX. Thuận An, Bình Dương',
    phone: '0888 999 111',
    contact_type: 'zalo',
    country: 'VN',
    description: 'Nhà máy sản xuất đồ da xuất khẩu, túi xách nữ cao cấp. Có chứng chỉ ISO, xuất hàng Nhật, Hàn.',
  },
  {
    name: 'Túi Xách Đồng Nai',
    url: 'https://tuixachdn.vn/san-pham',
    price: 95000,
    currency: 'VND',
    moq: 200,
    rating: 4.2,
    years_on_platform: 3,
    location: 'TP. Biên Hòa, Đồng Nai',
    phone: '0905 678 234',
    contact_type: 'zalo',
    country: 'VN',
    description: 'Xưởng may túi xách giá rẻ, chuyên hàng sỉ cho chợ đầu mối. MOQ thấp, giao hàng nhanh nội địa.',
  },
  {
    name: 'Minh Châu Bags',
    url: 'https://minhchaubags.com/collections',
    price: 280000,
    currency: 'VND',
    moq: 80,
    rating: 4.6,
    years_on_platform: 5,
    location: 'Quận 12, TP. Hồ Chí Minh',
    phone: '0933 456 789',
    contact_type: 'zalo',
    country: 'VN',
    description: 'Thiết kế và sản xuất túi xách nữ thời trang. Nhận OEM/ODM, đa dạng mẫu mã, cập nhật trend.',
  },

  // ========== 2 XƯỞNG CAMPUCHIA — USD ==========
  {
    name: 'Phnom Penh Leather Co.',
    url: 'https://ppleather.com.kh/products',
    price: 8.50,
    currency: 'USD',
    moq: 200,
    rating: 4.0,
    years_on_platform: 3,
    location: 'Phnom Penh, Campuchia',
    phone: '+855 12 345 678',
    contact_type: 'phone',
    country: 'KH',
    description: 'Xưởng da Phnom Penh, chuyên túi xách giá rẻ xuất khẩu sang Việt Nam và Thái Lan. Nhân công giá tốt.',
  },
  {
    name: 'Siem Reap Bags Factory',
    url: 'https://sremapbags.com.kh/catalog',
    price: 5.20,
    currency: 'USD',
    moq: 300,
    rating: 3.8,
    years_on_platform: 2,
    location: 'Siem Reap, Campuchia',
    phone: '+855 98 765 432',
    contact_type: 'phone',
    country: 'KH',
    description: 'Xưởng sản xuất túi vải và da tổng hợp. Giá cạnh tranh nhờ chi phí nhân công thấp, giao hàng qua biên giới.',
  },

  // ========== 5 XƯỞNG TRUNG QUỐC — CNY ==========
  {
    name: '广州锐尚皮具厂',
    url: 'https://detail.1688.com/offer/abc123.html',
    price: 38,
    currency: 'CNY',
    moq: 100,
    rating: 4.7,
    years_on_platform: 7,
    location: 'Quảng Châu, Quảng Đông',
    phone: 'wx_ruishang_bags',
    contact_type: 'wechat',
    country: 'TQ',
    description: '广州白云区皮具工厂，专业生产女士手袋，支持来图来样定制。Xưởng da Bạch Vân, chuyên túi xách nữ.',
  },
  {
    name: '义乌梦想箱包',
    url: 'https://detail.1688.com/offer/def456.html',
    price: 22,
    currency: 'CNY',
    moq: 300,
    rating: 4.3,
    years_on_platform: 5,
    location: 'Nghĩa Ô, Chiết Giang',
    phone: 'yw_dreambox88',
    contact_type: 'wechat',
    country: 'TQ',
    description: '义乌源头工厂，女包批发价格低，款式多更新快。Xưởng gốc Nghĩa Ô, giá cực thấp, mẫu đa dạng.',
  },
  {
    name: '深圳时尚皮具',
    url: 'https://detail.1688.com/offer/ghi789.html',
    price: 75,
    currency: 'CNY',
    moq: 50,
    rating: 4.9,
    years_on_platform: 10,
    location: 'Thâm Quyến, Quảng Đông',
    phone: 'sz_fashion_leather',
    contact_type: 'wechat',
    country: 'TQ',
    description: '高端真皮女包工厂，10年出口经验，品质保证。Xưởng da thật cao cấp, 10 năm xuất khẩu.',
  },
  {
    name: '温州博雅箱包',
    url: 'https://detail.1688.com/offer/jkl101.html',
    price: 35,
    currency: 'CNY',
    moq: 150,
    rating: 4.4,
    years_on_platform: 6,
    location: 'Ôn Châu, Chiết Giang',
    phone: 'wz_boya_bags',
    contact_type: 'wechat',
    country: 'TQ',
    description: '温州箱包厂家直销，主营时尚女包，支持混批。Xưởng Ôn Châu bán trực tiếp, hỗ trợ đặt mix mẫu.',
  },
  {
    name: '河北冀皮工贸',
    url: 'https://detail.1688.com/offer/mno202.html',
    price: 18,
    currency: 'CNY',
    moq: 500,
    rating: 4.1,
    years_on_platform: 4,
    location: 'Hà Bắc, Hà Bắc',
    phone: 'hb_jipi_trade',
    contact_type: 'wechat',
    country: 'TQ',
    description: '源头低价工厂，帆布包牛津布包为主，量大价优。Xưởng giá gốc, chuyên túi vải canvas, giá tốt số lượng lớn.',
  },
];
